sudo: required
services: 
        -docker

script:
        - docker build -t rybalka/docker-react .
        - docker images rybalka/docker-react

before_deploy:
        - docker login - rybalka -p a1234567

docker:
        provider: script
        script: docker push rybalka/docker-react
        on:
                branch: master

